import Header from '@/components/dashboard/header'
import Sidebar from '@/components/dashboard/sidebar'
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'FlixHome Dashboard',
  description: 'Generated by create next app',
}

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="grid grid-cols-[262px_1fr] h-screen w-full bg-slate-50">
      <Sidebar />
      <div className="h-screen w-full">
        <Header />
        {children}
      </div>
    </div>
  )
}
